controller_list:
  - name: fake_group1_gantry_controller
    joints:
      - p_motion1
      - p_motion2
  - name: fake_group2_kuka_controller
    joints:
      - pleatrobot_joint_1
      - pleatrobot_joint_2
      - pleatrobot_joint_3
      - pleatrobot_joint_4
      - pleatrobot_joint_5
      - pleatrobot_joint_6
      - pleatrobot_joint_7
  - name: fake_group3_gripper_controller
    joints:
      - p_jaw2
      - c_rod3
      - c_rod1
  - name: fake_group4_complete_controller
    joints:
      - p_motion1
      - p_motion2
      - pleatrobot_joint_1
      - pleatrobot_joint_2
      - pleatrobot_joint_3
      - pleatrobot_joint_4
      - pleatrobot_joint_5
      - pleatrobot_joint_6
      - pleatrobot_joint_7